version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "toggl-deploy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17biwluhb0lj1"
s3_prefix = "toggl-deploy"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
